info:
  namespace: slimy_tree_taps
items:
  amber:
    display_name: slimy_tree_taps
    permission: slimy_tree_taps
    resource:
      material: PLAYER_HEAD
      generate: false
      model_id: 2200800
      model_path: "materials/amber"
  raw_plastic:
    display_name: slimy_tree_taps
    permission: slimy_tree_taps
    resource:
      material: PAPER
      generate: false
      model_id: 2200801
      model_path: "materials/raw_plastic"
  rubber:
    display_name: slimy_tree_taps
    permission: slimy_tree_taps
    resource:
      material: FIREWORK_STAR
      generate: false
      model_id: 2200802
      model_path: "materials/rubber"
  sticky_resin:
    display_name: slimy_tree_taps
    permission: slimy_tree_taps
    resource:
      material: BROWN_DYE
      generate: false
      model_id: 2200803
      model_path: "materials/sticky_resin"
  diamond_tree_tap:
    display_name: slimy_tree_taps
    permission: slimy_tree_taps
    resource:
      material: DIAMOND_HOE
      generate: false
      model_id: 2200804
      model_path: "treetap/diamond_tree_tap"
  reinforced_tree_tap:
    display_name: slimy_tree_taps
    permission: slimy_tree_taps
    resource:
      material: IRON_HOE
      generate: false
      model_id: 2200805
      model_path: "treetap/reinforced_tree_tap"
  tree_tap:
    display_name: slimy_tree_taps
    permission: slimy_tree_taps
    resource:
      material: WOODEN_HOE
      generate: false
      model_id: 2200806
      model_path: "treetap/tree_tap"
